### ISSUE TITLE
Extending native module for android

### ISSUE THREAD

**Issue by jolindroth** [mike-stewart-dev/expo-widgets#53]
In the example project, we have a `Module.swift` file. Upon modifying this file, we can successfully read the new functions by calling `requireNativeModule ` in our RN Context.

However, for android, there is no such file. And the ExpoWidgetsModule.kt from the expo-widgets package takes precedence even if we add a custom ExpoWidgetsModule.kt in our expo-widgets folder to try to overwrite it.

What is the recommended approach to extend the module with new functions on Android? In my case, I want to read from the shared storage from the RN Context which was easy to do through Module.swift on iOS.

**Comment by jolindroth** [comment]
Related to #24

**Comment by mike-stewart-dev** [comment]
Is it in your android widget folder at: src/main/java/package_name/ExpoWidgetsModule.kt

**Comment by jolindroth** [comment]
Yes! But there seems to be an incomplete implementation to copy over the ExpoWidgetsModule.kt , which is in android/withModule.ts. I think #24 tried to address that issue.

**Comment by jolindroth** [comment]
For anyone reading, as a temporary workaround I patched the ExpoWidgetModule.kt directly in the plugin, since it wouldn't use the one in the custom folder.

**Comment by jolindroth** [comment]
After trying to build for prod I noticed that we have a build error related to duplicate files. So the issue is actually that both the ExpoWidgetModule.kt from the custom folder and the ExpoWidgetModule.kt from the plugin folder is copied over, causing a conflict during build with ProGuard.

And the one from the plugin seems to take precedence at runtime.

```
ERROR: /home/expo/workingdir/build/node_modules/@bittingz/expo-widgets/android/build/intermediates/runtime_library_classes_jar/release/bundleLibRuntimeToJarRelease/classes.jar: R8: Type expo.modules.widgets.ExpoWidgetsModule$definition$lambda$3$$inlined$Function$4 is defined multiple times: /home/expo/workingdir/build/node_modules/@bittingz/expo-widgets/android/build/intermediates/runtime_library_classes_jar/release/bundleLibRuntimeToJarRelease/classes.jar:expo/modules/widgets/ExpoWidgetsModule$definition$lambda$3$$inlined$Function$4.class, /home/expo/workingdir/build/android/app/build/tmp/kotlin-classes/release/expo/modules/widgets/ExpoWidgetsModule$definition$lambda$3$$inlined$Function$4.class
```

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, origin: /home/expo/workingdir/build/node_modules/@bittingz/expo-widgets/android/build/intermediates/runtime_library_classes_jar/release/bundleLibRuntimeToJarRelease/classes.jar:expo/modules/widgets/ExpoWidgetsModule$definition$lambda$3$$inlined$Function$4.class
```

**Comment by mike-stewart-dev** [comment]
Please do a clean of your android folder (projRoot/android not the widget android folder) and update to the latest package version (2.9.0). This should be fixed now

**Comment by anthonylin198** [comment]
@jolindroth were you able to resolve the production duplicate files build error?

**Comment by xuanmai-agilityio** [comment]
@jolindroth  could you confirm the custom folder works on the latest version v3.0.1? I've tried adding several functions, but they're not available on the JS side. It still uses the default `ExpoWidgetModule.kt`.
